# Generated by Django 6.1.1 on 2026-10-04 09:52

import apps.orders.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.orders.models.new_reference, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('refunded', 'Received and refunded'), ('rejected', 'Rejected')], db_index=True, default='requested', max_length=20)),
                ('reason', models.CharField(choices=[('too_small', 'Too small'), ('too_large', 'Too large'), ('not_as_pictured', 'Not as pictured'), ('changed_mind', 'Changed my mind'), ('faulty', 'Faulty or damaged'), ('other', 'Other')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('staff_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='orders.orderline')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='returns.returnrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
