# Generated by Django 6.1.1 on 2026-10-04 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300, unique=True)),
                ('photographer', models.CharField(max_length=120)),
                ('photographer_url', models.URLField(max_length=300)),
                ('source_url', models.URLField(help_text='The page of the photo, for attribution.', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('opening_hours', models.CharField(blank=True, max_length=200)),
                ('timezone', models.CharField(max_length=60)),
                ('currency', models.CharField(max_length=3)),
                ('free_shipping_over', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('return_window_days', models.PositiveSmallIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('text', models.TextField(blank=True)),
                ('alt', models.CharField(max_length=200)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.photo')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
