# Generated by Django 6.1.1 on 2026-10-04 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('hex', models.CharField(help_text='Swatch colour, for example #c8b59a.', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=20)),
                ('system', models.CharField(choices=[('letter', 'Letters (XS to XL)'), ('shoe', 'Shoes (EU)'), ('one', 'One size')], max_length=10)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['system', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('department', models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('unisex', 'Unisex')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('active', 'On sale'), ('draft', 'Draft'), ('archived', 'Archived')], db_index=True, default='active', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=list, help_text='Short bullet points: fit, closures, pockets.')),
                ('composition', models.CharField(blank=True, max_length=200)),
                ('care', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='The old price, when the product is on sale.', max_digits=8, null=True)),
                ('is_new', models.BooleanField(default=False)),
                ('popularity', models.PositiveIntegerField(default=0, help_text='Higher comes first in the default sort.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-popularity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('alt', models.CharField(max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.photo')),
                ('products', models.ManyToManyField(blank=True, related_name='collections', to='catalog.product')),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('colour', models.ForeignKey(blank=True, help_text='The colour shown, if the photo is of one.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.colour')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.photo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('stock', models.IntegerField(default=0)),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.colour')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.size')),
            ],
            options={
                'ordering': ['product', 'colour__name', 'size__position'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('compare_at_price__isnull', True), ('compare_at_price__gt', models.F('price')), _connector='OR'), name='compare_at_price_above_price'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('product', 'colour', 'size'), name='unique_variant'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_not_negative'),
        ),
    ]
